export interface Leiloeiro {
  nome: string;
  url: string;
}

export const LEILOEIROS_CONFIAVEIS: Leiloeiro[] = [
  { nome: "PML Leilões", url: "https://pmlleiloes.com.br/" },
  { nome: "Jorge Brasil Leilões", url: "http://www.jorgebrasil.lel.br/" },
  { nome: "Müller Leilões", url: "http://www.mullerleiloes.com.br/" },
  { nome: "Fidalgo Leilões", url: "https://www.fidalgoleiloes.com.br/" },
  { nome: "Leilões da Justiça do Trabalho de SC", url: "https://www.trt12.jus.br/portal/areas/ascom/extranet/destaques/leiloes.jsp" },
  { nome: "Klöckner Leilões", url: "https://www.kleiloes.com.br/Agenda.aspx" },
  { nome: "João Emilio Leiloeiro", url: "https://joaoemilio.com.br/" },
  { nome: "Lance Leilões", url: "https://lancese.com.br/" },
  { nome: "Pestana Leilões", url: "https://www.leiloes.com.br/" },
  { nome: "Franco Leilões", url: "https://www.francoleiloes.com.br/" },
  { nome: "Valerio Iamin Leilões", url: "https://www.valerioiaminleiloes.com.br/" },
  { nome: "Peterlongo Leilões", url: "https://peterlongoleiloes.com.br/" },
  { nome: "Santos Leilões", url: "https://leilaosantos.com.br/" },
  { nome: "José Paulo Bonatto", url: "https://leiloeirobonatto.com/" },
  { nome: "Mário Lessa Freitas Filho", url: "https://www.lessaleiloes.com.br/" },
  { nome: "Sérgio Scholante", url: "https://www.scholanteleiloes.com.br/" },
  { nome: "NORTON LEILÕES", url: "https://nortonleiloes.com.br/externo/" },
  { nome: "Leilão Judicial Eletrônico", url: "https://leje.com.br/" },
  { nome: "Rymer Leilões", url: "https://www.rymerleiloes.com.br/" },
  { nome: "LanceJudicial", url: "https://www.lancejudicial.com.br/" },
  { nome: "MP Leilão", url: "https://www.mpleilao.com.br/" },
  { nome: "Raupp Leilões", url: "https://www.rauppleiloes.com.br/" },
  { nome: "Sold Leilões", url: "https://www.sold.com.br/" },
  { nome: "Mega Leilões", url: "https://www.megaleiloes.com.br/" },
  { nome: "Frazão Leilões", url: "https://www.frazaoleiloes.com.br/" },
  { nome: "Central Sul de Leilões", url: "https://www.centralsuldeleiloes.com.br/" },
  { nome: "Santa Maria Leilões", url: "https://www.santamarialeiloes.com.br/" },
  { nome: "Freitas Leiloeiro", url: "https://www.freitasleiloeiro.com.br/" },
  { nome: "Viva Leilões", url: "https://www.vivaleiloes.com.br/" },
  { nome: "Biasi Leilões", url: "https://www.biasileiloes.com.br/" },
  { nome: "LeilãoVIP", url: "https://www.leilaovip.com.br/" },
  { nome: "Sanches Leilões", url: "https://sanchesleiloes.com.br/externo/" },
  { nome: "Krieger Leilões", url: "https://kriegerleiloes.com.br/" },
  { nome: "Seu Imóvel BB", url: "https://seuimovelbb.com.br/" },
  { nome: "Sato Leilões", url: "https://satoleiloes.com.br/" },
  { nome: "Cravo Leilões", url: "https://www.cravoleiloes.com.br/" },
  { nome: "Renovar Leilões", url: "https://www.renovarleiloes.com.br/" },
  { nome: "Zukerman Leilões", url: "https://www.zukerman.com.br/" },
  { nome: "Agência de Leilões", url: "https://www.agenciadeleiloes.com.br/" },
  { nome: "Superbid Exchange", url: "https://www.superbid.net/" },
  { nome: "Grandes Leilões", url: "https://www.grandesleiloes.com.br/" },
  { nome: "HAMMER", url: "https://hammer.lel.br/" },
  { nome: "3 Torres Leilões", url: "https://www.3torresleiloes.com.br/" },
  { nome: "Hasta Leilões", url: "https://www.hastaleiloes.com.br/" },
  { nome: "Lance Certo Leilões", url: "https://www.lancecertoleiloes.com.br/" },
  { nome: "Tonial Leilões", url: "https://www.tonialleiloes.com.br/" },
  { nome: "Balbino Leilões", url: "https://www.balbinoleiloes.com.br/externo/" },
  { nome: "Kronberg Leilões", url: "https://www.kronbergleiloes.com.br/" },
  { nome: "Spencer Leilões", url: "https://spencerleiloes.com.br/" },
  { nome: "SCHMITZ Leiloeiros", url: "https://www.clicleiloes.com.br/" },
  { nome: "D1LANCE Leilões", url: "https://www.d1lance.com.br/" },
  { nome: "Hasta Pública Leilões", url: "https://www.hastapublica.lel.br/leilao/lotes/imoveis" },
  { nome: "Banrisul Leilões", url: "https://www.banrisul.com.br/bob/link/bobw10hn_leiloes_comprar.aspx?secao_id=137" },
  { nome: "123 Leilões", url: "https://www.123leiloes.com.br/" },
  { nome: "Santander Imóveis", url: "https://www.santanderimoveis.com.br/" },
  { nome: "Imóveis Inter", url: "https://imoveis.bancointer.com.br/" },
  { nome: "Deonizia Leilões", url: "https://www.deonizialeiloes.com.br/externo/" },
  { nome: "NAKAKOGUE Leilões", url: "https://www.nakakogueleiloes.com.br/" },
  { nome: "Machado Leilões", url: "https://www.machadoleiloes.com.br/" },
  { nome: "Moraes Leilões", url: "https://www.moraesleiloes.com.br/" },
  { nome: "Patrícia Andrade", url: "https://www.patricialeiloeira.com.br/" },
  { nome: "O Leilões", url: "https://oleiloes.com.br/" },
  { nome: "GP Leilões", url: "https://www.gpleiloes.com.br//#/" },
  { nome: "Baldissera Leiloeiros", url: "https://www.baldisseraleiloeiros.com.br/" },
  { nome: "Stefanelli Leilões", url: "https://www.stefanellileiloes.com.br/" },
  { nome: "WR Leilões", url: "https://www.wrleiloes.com.br/" },
  { nome: "HD Leilões", url: "https://www.hdleiloes.com.br/externo/" },
  { nome: "Casa Leiloeira", url: "https://www.casaleiloeira.com.br/" },
  { nome: "Leilões Centro Oeste", url: "https://www.leiloescentrooeste.com.br/externo/" },
  { nome: "Álvaro Leilões", url: "https://www.alvaroleiloes.com.br/externo/" },
  { nome: "Fabio Barbosa Leilões", url: "https://www.fabiobarbosaleiloes.com.br/externo/" },
  { nome: "RJ Leilões", url: "https://www.rjleiloes.com.br/" },
  { nome: "Vitrine Bradesco", url: "https://banco.bradesco/html/classic/produtos-servicos/leiloes/index.shtm" },
  { nome: "Milan Leilões", url: "https://www.milanleiloes.com.br/" },
  { nome: "Palácio dos Leilões", url: "https://www.palaciodosleiloes.com.br/" },
  { nome: "Leilões Brasil", url: "https://www.leiloesbrasil.com.br/" },
  { nome: "Norte Leilões", url: "https://www.norteleiloes.com.br/" },
  { nome: "LB LEILÕES", url: "https://www.lbleiloes.com.br/" },
  { nome: "Globo Leilões", url: "https://www.globoleiloes.com.br/" },
  { nome: "Veronica Telles", url: "https://www.veronicaleiloes.com.br/" },
  { nome: "VIP Leilões", url: "https://www.vipleiloes.com.br/" },
  { nome: "Hasta VIP", url: "https://www.hastavip.com.br/" },
  { nome: "Max Leilões", url: "https://www.maxxleiloes.com.br/" },
  { nome: "Delta Leilões", url: "https://www.delttaleiloes.com.br/home" },
  { nome: "Krobel Leilões", url: "https://www.krobelleiloes.com.br/" },
  { nome: "Mazzolli Leilões", url: "https://mazzollileiloes.com.br/home" },
  { nome: "Oeste Leilões", url: "https://www.oesteleiloes.com.br/home" },
  { nome: "Pizzolatti Leilões", url: "https://www.topleiloes.com.br/" },
  { nome: "Damiani Leilões", url: "https://www.damianileiloes.com.br/home" },
  { nome: "Pimentel Leilões", url: "https://www.pimentelleiloes.com.br/" },
  { nome: "BSP Leilões", url: "https://www.bspleiloes.com.br/Principal.asp" },
  { nome: "PSN Leilões", url: "https://www.psnleiloes.com.br/" },
  { nome: "Nordeste Leilões", url: "https://www.nordesteleiloes.com.br/" },
  { nome: "Leilão Brasil", url: "https://www.leilaobrasil.com.br/" },
  { nome: "Saraiva Leilões", url: "https://www.saraivaleiloes.com.br/" },
  { nome: "Becker Leilões", url: "https://www.fbleiloes.com.br/home" }
];

export const FERRAMENTAS_UTEIS = [
  { nome: "Informe Cadastral", url: "https://www.informecadastral.com.br/" },
  { nome: "Registro de Imóveis do Brasil - Calculadora", url: "https://www.registrodeimoveis.org.br/calculadora" },
  { nome: "SAEC - Registradores - ONR", url: "https://registradores.onr.org.br/" },
  { nome: "Acompanhamentos Processos - Jusbrasil", url: "https://www.jusbrasil.com.br/acompanhamentos/processos" },
  { nome: "BCB - Calculadora do Cidadão", url: "https://www3.bcb.gov.br/CALCIDADAO/publico/exibirFormCorrecaoValores.do?method=exibirFormCorrecaoValores" }
];
